### PR TITLE
Fix #16: StringSearchInterpolator does not cache answers.

### LINKED ISSUE #16: StringSearchInterpolator does not cache answers
`StringSearchInterpolator`'s `cacheAnswers` has no effect at all, since `existingAnswers` Map is never populated.

### PR DESCRIPTION
**Pull request by belingueres**
- Added tests exposing the issue.
- Fixed code.
- Added missing @Override annotations.

### CODE REVIEW

**Comment by khmarbaise** [comment]
That looks great, but could you separate the fix of override and the test into separate pull request...I appreciate to merge that...Thanks for helping..

**Comment by belingueres** [comment]
Do you mean only the extra @Override in another PR?

**Review by gnodet — APPROVED** [review]
LGTM, the conflicts will have to be solved before merging obviously.

**Comment by belingueres** [comment]
Rebased & squashed.

**Review by slachiewicz — APPROVED** [review]

**Pull request merged**
