### PR TITLE
Fixed MultiDelimiterStringSearchInterpolator escape String code

### PR DESCRIPTION
**Pull request by belingueres**

### CODE REVIEW

**Comment by khmarbaise** [comment]
If I correctly understand this fixed #3 ? If yes than it would be great to mention something like:
```
Fixed #3
 o Explanations
```
Using the `Fixed #3` will automatically close the related issue if i merge this into the code base...

**Comment by khmarbaise** [comment]
Is this related to issue #3 ? It does not look like. So it would be great to make a separate issue for that and a separate pull request otherwise it's hard follow changes and the history in git...and also for end users which issue fixes what in detail...

**Comment by belingueres** [comment]
Hi!
Thanks for reviewing the patch. 
My only intention was only that all tests to pass. Looking at issue #3, it seems somebody commited the only one test failing and this patch fixes it (however I'm not sure if this is the correct behavior or the library). I just added the code to make the test pass and added one test with the double escape character in different order.

**Comment by belingueres** [comment]
Hi!
Added a new commit to solve issue #5. (Don't know how to separate it from the first pull request yet.)

**Comment by belingueres** [comment]
Hi @khmarbaise:
Now that I'm a little more experienced with git (oopss), would you agree if I close this pull request and start all over again? (fixing each bug inside their own branch?)
Best Regards,
Gabriel

**Comment by khmarbaise** [comment]
Great...If you like sure..and yes fixing each issue in it's own branch makes sense...

**Comment by belingueres** [comment]
Replace by PR #7 and #8. This PR will be closed now.

**Pull request closed without merging**
