### PR TITLE
Add FeedbackingValueSource

### PR DESCRIPTION
**Pull request by errandir**

### CODE REVIEW

**Comment by belingueres** [comment]
Please open an issue explaining the value proposition of this PR.
Regards,
Gabriel

**Comment by errandir** [comment]
The issue opened: #22

**Comment by slachiewicz** [comment]
@gnodet can You check it?

**Review by gnodet — APPROVED** [review]
LGTM, though it's of low use on its own, it'll have to be leveraged in maven.
For maven 4, I was wondering about exposing an interpolation service in the V4 API though (it could leverage the plexus-interpolation as an implementation).

**Review by slachiewicz — APPROVED** [review]

**Pull request merged**
